### ISSUE TITLE
Regarding measurements etc... have you seen Manipulator workbench ?

### ISSUE THREAD

**Issue by luzpaz** [AlansCodeLog/freecad-useful-panel#1]
https://github.com/easyw/Manipulator/issues

**Comment by AlansCodeLog** [comment]
Yes, but I did not find I didn't like it. The measuring tools just seemed like a variant of the built in measure tools, which I also did not like. I don't want to have to care about what type of measurement I'm taking, or having them be saved in the document. Maybe I did not make it clear in the readme, but the addon just listens to the selection changes and auto updates, there's no need to do anything more than make a selection.

I used to use Fusion, and I liked that it would automatically give you some useful measurements in the corner based on your selection. It was really quick and useful.

I plan to add diameter/radius soon, so that except for angles which I have never found myself measuring, I won't need to use the measuring tools. I can just select and glance at the panel (or the corner, once I figure out how to do that).
